name: Ubuntu 18.04 (GCC, MPICH, Python)
run-name: ubuntu-bionic

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '*.md'
      - 'source/docs/**'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '*.md'
      - 'source/docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release
  ELFUTILS_DOWNLOAD_VERSION: 0.183
  OMNITRACE_CI: ON
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
  OMNITRACE_TMPDIR: "%env{PWD}%/testing-tmp"

jobs:
  ubuntu-bionic:
    runs-on: ubuntu-latest
    container:
      image: jrmadsen/omnitrace:ci-base-ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        compiler: ['g++-7', 'g++-8']
        mpi: [ 'nompi', 'mpich' ]

    steps:
    - name: Patch Git
      timeout-minutes: 25
      run: |
        apt-get update
        apt-get install -y software-properties-common
        add-apt-repository -y ppa:git-core/ppa
        apt-get update
        apt-get upgrade -y
        apt-get install -y git

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Packages
      timeout-minutes: 25
      uses: nick-fields/retry@v2
      with:
        retry_wait_seconds: 30
        timeout_minutes: 25
        max_attempts: 5
        command: |
          apt-get update &&
          apt-get upgrade -y &&
          apt-get install -y build-essential m4 autoconf libtool python3-pip ${{ matrix.compiler }} &&
          if [ "${{ matrix.mpi }}" = "mpich" ]; then apt-get install -y libmpich-dev mpich; fi &&
          if [ "${{ matrix.mpi }}" = "openmpi" ]; then apt-get install -y libopenmpi-dev openmpi-bin libfabric-dev; fi &&
          python3 -m pip install --upgrade pip &&
          python3 -m pip install numpy &&
          python3 -m pip install perfetto &&
          python3 -m pip install 'cmake==3.16.3' &&
          for i in 6 7 8 9 10; do /opt/conda/envs/py3.${i}/bin/python -m pip install numpy perfetto dataclasses; done

    - name: Install Kokkos
      timeout-minutes: 10
      run:
        cd examples/lulesh/external/kokkos &&
        cmake -B build -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_SERIAL=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_STANDARD=17 . &&
        cmake --build build --target all --parallel 2 &&
        cmake --build build --target install &&
        rm -rf build

    - name: Configure Env
      run:
        echo "CC=$(echo '${{ matrix.compiler }}' | sed 's/+/c/g')" >> $GITHUB_ENV &&
        echo "CXX=${{ matrix.compiler }}" >> $GITHUB_ENV &&
        echo "/opt/omnitrace/bin:${HOME}/.local/bin" >> $GITHUB_PATH &&
        echo "LD_LIBRARY_PATH=/opt/omnitrace/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV

    - name: Configure, Build, and Test
      timeout-minutes: 115
      shell: bash
      run:
        git config --global --add safe.directory ${PWD} &&
        cmake --version &&
        if [ "${{ matrix.mpi }}" = "nompi" ]; then USE_MPI=OFF; else USE_MPI=ON; fi &&
        append-tagname() { if [ "${1}" == "ON" ]; then TAG="${TAG}-${2}"; fi; } &&
        python3 ./scripts/run-ci.py -B build
          --name ${{ github.repository_owner }}-${{ github.ref_name }}-ubuntu-bionic-${{ matrix.compiler }}-${{ matrix.mpi }}-python
          --build-jobs 2
          --site GitHub
          --
          -DCMAKE_C_COMPILER=$(echo '${{ matrix.compiler }}' | sed 's/+/c/g')
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DCMAKE_INSTALL_PREFIX=/opt/omnitrace
          -DOMNITRACE_BUILD_TESTING=ON
          -DOMNITRACE_BUILD_DYNINST=OFF
          -DOMNITRACE_USE_MPI=${USE_MPI}
          -DOMNITRACE_USE_HIP=OFF
          -DOMNITRACE_USE_PYTHON=ON
          -DOMNITRACE_PYTHON_PREFIX=/opt/conda/envs
          -DOMNITRACE_PYTHON_ENVS="py3.6;py3.7;py3.8;py3.9;py3.10"
          -DLULESH_BUILD_KOKKOS=OFF
          -DOMNITRACE_MAX_THREADS=64
          -DOMNITRACE_DISABLE_EXAMPLES="transpose;rccl"
          -DOMNITRACE_BUILD_NUMBER=${{ github.run_attempt }}

    - name: Install
      run:
        cmake --build build --target install --parallel 2

    - name: Test Install
      timeout-minutes: 10
      run: |
        set -v
        export OMNITRACE_DEBUG=ON
        which omnitrace-avail
        ldd $(which omnitrace-avail)
        omnitrace-avail --help
        omnitrace-avail -a
        which omnitrace-critical-trace
        ldd $(which omnitrace-critical-trace)
        which omnitrace
        ldd $(which omnitrace)
        omnitrace --help
        omnitrace -e -v 1 -o ls.inst --simulate -- ls
        for i in $(find omnitrace-ls.inst-output -type f); do echo -e "\n\n --> ${i} \n\n"; cat ${i}; done
        omnitrace -e -v 1 -o ls.inst -- ls
        ./ls.inst
        omnitrace -e -v 1 --simulate -- ls
        for i in $(find omnitrace-ls-output -type f); do echo -e "\n\n --> ${i} \n\n"; cat ${i}; done
        omnitrace -e -v 1 -- ls

    - name: Test User API
      timeout-minutes: 10
      run: |
        set -v
        ./scripts/test-find-package.sh --install-dir /opt/omnitrace

    - name: CTest Artifacts
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: ctest-${{ github.job }}-log
        path: |
          build/*.log

    - name: Data Artifacts
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: data-${{ github.job }}-files
        path: |
          build/omnitrace-tests-config/*.cfg
          build/omnitrace-tests-output/**/*.txt
          build/omnitrace-tests-output/**/*-instr*.json

    - name: Kill Perfetto
      if: success() || failure()
      continue-on-error: True
      run: |
        set +e
        RUNNING_PROCS=$(pgrep trace_processor_shell)
        if [ -n "${RUNNING_PROCS}" ]; then kill -s 9 ${RUNNING_PROCS}; fi
